### PR TITLE
Issues/24 and other fixes

### LINKED ISSUE #20: Add logging

### LINKED ISSUE #22: Caller id is not in the expected format
Using current master (ceb8f362bc) with Puppet-generated certs and a configuration like [this](https://gist.github.com/jantman/c63d956c3964eabf75ba), I try this:

    conf_path = '/home/jantman/.mcollective.dev'
    conf = config.Config.from_configfile(conf_path)
    msg = message.Message(body='ping', agent='discovery', config=conf)
    logger.debug("sending ping")
    res = rpc.SimpleAction(config=conf, msg=msg, agent='discovery').call(timeout=60)
    print(res)

But I end up hitting the timeout with no messages received (and the ActiveMQ admin confirms 0 messages enqueued to the reply queue). On my mcollective servers, I have a warning log message:

```
W, [2014-07-24T08:38:00.890263 #14523]  WARN -- : runner.rb:193:in `receiver_thread' Failed to handle message: Caller id is not in the expected format - RuntimeError
W, [2014-07-24T08:38:00.890562 #14523]  WARN -- : runner.rb:194:in `receiver_thread' /usr/libexec/mcollective/mcollective/security/ssl.rb:262:in `public_key_file'
        /usr/libexec/mcollective/mcollective/security/ssl.rb:177:in `validrequest?'
        /usr/libexec/mcollective/mcollective/security/ssl.rb:95:in `decodemsg'
        /usr/lib/ruby/site_ruby/1.8/mcollective/message.rb:178:in `decode!'
        /usr/lib/ruby/site_ruby/1.8/mcollective/runner.rb:217:in `receive'
        /usr/lib/ruby/site_ruby/1.8/mcollective/runner.rb:172:in `receiver_thread'
        /usr/lib/ruby/site_ruby/1.8/mcollective/runner.rb:170:in `loop'
        /usr/lib/ruby/site_ruby/1.8/mcollective/runner.rb:170:in `receiver_thread'
        /usr/lib/ruby/site_ruby/1.8/mcollective/runner.rb:137:in `start_receiver_thread'
        /usr/lib/ruby/site_ruby/1.8/mcollective/runner.rb:137:in `initialize'
        /usr/lib/ruby/site_ruby/1.8/mcollective/runner.rb:137:in `new'
        /usr/lib/ruby/site_ruby/1.8/mcollective/runner.rb:137:in `start_receiver_thread'
        /usr/lib/ruby/site_ruby/1.8/mcollective/runner.rb:59:in `main_loop'
        /usr/lib/ruby/site_ruby/1.8/mcollective/unix_daemon.rb:30:in `daemonize_runner'
        /usr/lib/ruby/site_ruby/1.8/mcollective/unix_daemon.rb:13:in `daemonize'
        /usr/lib/ruby/site_ruby/1.8/mcollective/unix_daemon.rb:5:in `fork'
        /usr/lib/ruby/site_ruby/1.8/mcollective/unix_daemon.rb:5:in `daemonize'
        /usr/lib/ruby/site_ruby/1.8/mcollective/unix_daemon.rb:20:in `daemonize_runner'
```

The important part appears to be `Failed to handle message: Caller id is not in the expected format`.

### LINKED ISSUE #24: TypeError: string indices must be integers, not str
I've installed pymco and its dependencies in a new, clean virtualenv. I copy my client.cfg to the current directory, and run the simple_action.py example script (https://github.com/rafaduran/python-mcollective/blob/master/examples/simple_action.py). I get the following traceback:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jantman/tickets/PUPPET-193/botutladm1_venv/lib/python2.7/site-packages/stomp/transport.py", line 491, in __receiver_loop
    self.process_frame(f, frame)
  File "/home/jantman/tickets/PUPPET-193/botutladm1_venv/lib/python2.7/site-packages/stomp/transport.py", line 407, in process_frame
    self.notify(frame_type, f.headers, f.body)
  File "/home/jantman/tickets/PUPPET-193/botutladm1_venv/lib/python2.7/site-packages/stomp/transport.py", line 469, in notify
    rtn = notify_func(headers, body)
  File "/home/jantman/tickets/PUPPET-193/botutladm1_venv/src/python-mcollective/pymco/listener.py", line 85, in on_message
    self.responses.append(self.security.decode(body))
  File "/home/jantman/tickets/PUPPET-193/botutladm1_venv/src/python-mcollective/pymco/security/__init__.py", line 64, in decode
    return self.verify(self.deserialize(msg))
  File "/home/jantman/tickets/PUPPET-193/botutladm1_venv/src/python-mcollective/pymco/security/ssl.py", line 44, in verify
    hash_ = SHA.new(msg[':body'].encode('utf8'))
TypeError: string indices must be integers, not str
```

In addition, since this is an exception in a thread, the python process hangs indefinitely (won't handle Ctrl+C) and needs to be manually killed.

### PR DESCRIPTION
**Pull request by jantman**
This rolls together a number of fixes I'm working on:
* fixes #20 by adding a bunch of logging
* fixes #22 for me
* fixes #24 by making sure that messages are properly base64 decoded when received
* fixes another issue by converting PEM server certificates to the required DER format
* fixes an issue where Config.getboolean doesn't recognize 'yes' as a True value
* if the Listener thread gets an exception decoding the message, catch and log it. Otherwise, the python process locks up and needs to be manually killed (issue with uncaught exceptions in threads)

With all of this work, the 'simple_action.py' example now works in my environment.

### CODE REVIEW

**Comment by rafaduran** [comment]
I'm still getting issues with integration tests, specially with SSL security provider; I couldn't find the problem yet...

**Comment by rafaduran** [comment]
@jantman I'm having two different kind of issues:

* tavis-ci on my branch jantman-issues/24 (based on this pull request, with some fixes, mostly unit tests) seems to be failing in a non deterministic way

* Running integration tests in my development environment always get stuck at tests/integration/base.py::TestWithSSLMCo20x::test_ping_call

Latter issue I think may be related to the use threading.Condition in the listener, leading in some way to a deadlock. In ntteurope/kombu-stomp I've also had to solve a similar problem, using a generator in that case, so I considering changing how the listener works (I think the generator is a much better solution than threading.Condition). However, I'm just guessing... travis-ci will be fine (hopefully) when this is solved.

**Comment by rafaduran** [comment]
@jantman could you please check my branch jantman-issues/24 caab4781f125748a4d5c12137b15855fb511d938? My development environment it's fine with it and travis-ci too (thought I still see some timeout errors).

**Comment by jantman** [comment]
@rafaduran this branch seems to work fine for me, except for the ruby sym ":"s - on my branch I see result dicts returned with keys "body", "hash", "senderagent", etc. but on yours I see ":body", ":hash", ":senderagent", etc. - that's a bit unclean, but it works, and I can work with it, so I'd say it's good for me.

I haven't been using the integration tests, as they don't seem to accurately reflect my environment; I've been running directly against my Puppet-based mco instance.

**Comment by rafaduran** [comment]
@jantman you see the keys with leading colon ( :body, :hash, ...) because of my last change. This is required because depending on Puppet and/or Ruby versions (not really sure which one), Ruby symbols can be serialized as ":symbol" or "!ruby/sym symbol" and since PyYAML treats the former as an string, the latter must be translated into string too for compatibility reasons.

I think this is ready now, so I will check do some final checks (test coverage, documentation,..) and I will merge and release as soon as I can.

**Comment by jantman** [comment]
@rafaduran ok, thanks. Personally I think it would be nice if pymco stripped that out before returning results to the user (i.e. both ":symbol" and "!ruby/sym symbol" are returned as "symbol") but I supposed that could get confusing for the user to debug...

**Comment by rafaduran** [comment]
@jantman I did one last change (hopefully) before merging and it would be great if you can re-test it, could you please pull from my branch and test it again? It's mostly minor changes but I'm also using Python ssl PEM to DER functionality; if it works fine, I'd rather use it, thought I have no integration tests for that yet.

**Comment by jantman** [comment]
@rafaduran Ok, I'm running that at 5078dd930ffde262ebeea09da59c7e059558d071 ...

I don't know why I didn't remember this before, but... I tried this before as well, and spent quite a while on it, before I decided to use PyCrypto. This does __not__ work for me:
```
[ERROR listener.py:105 -           on_message() ] RSA key format is not supported
Traceback (most recent call last):
  File "/home/jantman/tickets/PUPPET-193/botutladm1_venv/src/python-mcollective/pymco/listener.py", line 98, in on_message
    decoded = self.security.decode(body, b64=useb64)
  File "/home/jantman/tickets/PUPPET-193/botutladm1_venv/src/python-mcollective/pymco/security/__init__.py", line 77, in decode
    return self.verify(deserialized)
  File "/home/jantman/tickets/PUPPET-193/botutladm1_venv/src/python-mcollective/pymco/security/ssl.py", line 55, in verify
    verifier = PKCS1_v1_5.new(self.server_public_key)
  File "/home/jantman/tickets/PUPPET-193/botutladm1_venv/src/python-mcollective/pymco/security/ssl.py", line 110, in server_public_key
    cache=self._server_public_key)
  File "/home/jantman/tickets/PUPPET-193/botutladm1_venv/src/python-mcollective/pymco/security/ssl.py", line 102, in _load_rsa_key
    cache = self._server_public_key = utils.load_rsa_key(self.config[key])
  File "/home/jantman/tickets/PUPPET-193/botutladm1_venv/src/python-mcollective/pymco/utils.py", line 70, in load_rsa_key
    k = RSA.importKey(content)
  File "/home/jantman/tickets/PUPPET-193/botutladm1_venv/lib/python2.7/site-packages/Crypto/PublicKey/RSA.py", line 680, in importKey
    return self._importKeyDER(externKey)
  File "/home/jantman/tickets/PUPPET-193/botutladm1_venv/lib/python2.7/site-packages/Crypto/PublicKey/RSA.py", line 588, in _importKeyDER
    raise ValueError("RSA key format is not supported")
ValueError: RSA key format is not supported
```
I'd tried this _exact_ same thing in https://github.com/jantman/python-mcollective/commit/40135e985c3bf368ae62d0d6e977cb56549651bc and found that, unfortunately, ``ssl.PEM_cert_to_DER_cert()``  doesn't support X.509 certificates, like the PEM files that a Puppet-based mco setup will use. Hence my use of PyCrypto to convert. For reference, see that commit and http://stackoverflow.com/a/12921889

There's also one other remaining issue from my point of view, the requirements - pycrypto and PyYAML aren't installed by pip, so scripts fail and then I have to install them manually. Ideally I think they should just be included in the requirements. I think I remember you having some concerns about that... maybe this is a good place to use setuptools [extras](https://pythonhosted.org/setuptools/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies)? I'd be happy to cut another PR with an example of how to do that if you're not familiar with it.

**Comment by rafaduran** [comment]
@jantman ok, I will remove last commit and I will use your implementation for PEM to DER conversion. About pycrypto and PyYAML in requirements, pycrypto is already in ``ssl`` extras and I will add PyYAML. Thank you for your help, I really appreciate your time spent here!

**Comment by rafaduran** [comment]
This is now merged.

**Pull request closed without merging**
